AppBundle\Entity\LogRecord:
    type: entity
    table: log_records
    repositoryClass: AppBundle\Entity\Repository\LogRecordRepository
    id:
        id:
            type: integer
            generator: { strategy: AUTO }

    fields:
        datetime:
            type: datetime
        record:
            type: string
            length: 2000